# Generated by Django 4.2.9 on 2024-02-28 16:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dgz5gpe5z/image/upload/v1708453621/owy10e5dfvswqrozcc1m.png', max_length=255, verbose_name='image'),
        ),
    ]
