# Generated by Django 4.2.9 on 2024-02-15 18:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
